### ISSUE TITLE
CI_ENVIRONMENT_NAME env variable not detected

### ISSUE THREAD

**Issue by aexvir** [kiwicom/crane#18]
It seems that the Datadog hook it's triggered even if it's not needed. The `CI_ENVIRONMENT_NAME` is a GitLab CI variable and it should be detected independently of the datadog hook trigger, but the error just appears there.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/crane-3.2.0-py3.7.egg/crane/hooks/base.py", line 25, in dispatch
    handler()
  File "/usr/local/lib/python3.7/site-packages/crane-3.2.0-py3.7.egg/crane/hooks/datadog.py", line 32, in create_event
    "environment:{0}".format(environ["CI_ENVIRONMENT_NAME"]),
  File "/usr/local/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
```

**Comment by aexvir** [comment]
Nevermind, the job actually has a datadog key, that's why it's triggered.
