### ISSUE TITLE
gitdb.exc.BadName: Ref 'master-93b091e2' did not resolve to an object

### ISSUE THREAD

**Issue by onedr0p** [kiwicom/crane#8]
Hi,

I have tried to use the 3.1.0 version of the image like I was doing in previous 2.x versions but I am getting an error:

```Fetching changes...
Checking out 93b091e2 as master...
Skipping Git submodules setup
$ crane --env 1a4481 --stack mystack --service myservice --new-image "$ARTIFACTORY_REG:$CI_BUILD_REF_SLUG-${CI_COMMIT_SHA:0:8}"
Traceback (most recent call last):
  File "/usr/local/bin/crane", line 11, in <module>
    load_entry_point('crane==3.1.0', 'console_scripts', 'crane')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/crane-3.1.0-py3.6.egg/crane/cli.py", line 49, in main
  File "/usr/local/lib/python3.6/site-packages/crane-3.1.0-py3.6.egg/crane/models.py", line 59, in load_from_settings
  File "/usr/local/lib/python3.6/site-packages/crane-3.1.0-py3.6.egg/crane/models.py", line 104, in check_preconditions
  File "/usr/local/lib/python3.6/site-packages/crane-3.1.0-py3.6.egg/crane/models.py", line 81, in new_commit
  File "/usr/local/lib/python3.6/site-packages/git/repo/base.py", line 460, in commit
    return self.rev_parse(text_type(rev) + "^0")
  File "/usr/local/lib/python3.6/site-packages/git/repo/fun.py", line 213, in rev_parse
    obj = name_to_object(repo, rev[:start])
  File "/usr/local/lib/python3.6/site-packages/git/repo/fun.py", line 147, in name_to_object
    raise BadName(name)
gitdb.exc.BadName: Ref 'master-93b091e2' did not resolve to an object
```

This looks like a issue using `$CI_BUILD_REF_SLUG-${CI_COMMIT_SHA:0:8}`. We have a requirement to include the branch name and git commit hash in the tag.

**Comment by onedr0p** [comment]
A simple fix for now would be to indent this in `crane/models.py` to be part of the `else`

```python
self.check_preconditions()
```

**Comment by underyx** [comment]
Hey @onedr0p!

Rest assured, we *are* thinking about how to fix this issue. Your proposed workaround wouldn't quite work all that well: this image tag makes it impossible for us to detect what the currently running version is, which is required for 70% of the code (all the hooks depend on this, even the echo hook for printing upgrade status since v3.) So if someone enables any further features in Crane, or hits a different branch than the happy upgrade path, they would probably be handed a random cryptic traceback.

So one thing I can imagine we could do, that wouldn't make that big of a mess in the code, is to set a flag that crane is running in 'limited mode' and disable hooks and everything other than the basic upgrade API calls when no commit references are available. Would that work for you?

**Comment by onedr0p** [comment]
@underyx that would work well, thanks.

**Comment by cloudlady911** [comment]
I am also getting this error.  We have a requirement to tag each container a certain way:

$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_BUILD_REF_NAME-$CI_PIPELINE_ID.  

This issue is forcing me back to using rancher-gitlab-deploy.

**Comment by chauffer** [comment]
@underyx any plan to address this issue?

**Comment by aexvir** [comment]
@onedr0p Good news! We got a contribution from @chauffer fixing this issue. Tomorrow we will release the new version. Thanks for bearing with us for so long.
